JoiaDaEuropa/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/profile/index'
  get '/home/index'
  get '/client_area/index'
  #get '/search'

  get '/client_area/edit_client'
  patch '/client_area/save_client'

  get '/order/recent'
  get '/order/hold'
  get '/order/cancel'
  get '/order/end'
  get '/order/detail/:id', to: 'order#detail', as: 'order_detail'
  get '/order/edit/:id', to: 'order#edit', as: 'order_edit'
  post '/order/update'
  get '/order/new'
  get '/order/all'
  post '/order/create'


  root to: 'home#index'
  
end

JoiaDaEuropa/app/controllers/client_area_controller.rb
class ClientAreaController < ApplicationController

  before_action :check_client

  def index

    @client = current_user.client

  end

  def edit_client

    @client = current_user.client

  end

  def save_client

    @client = current_user.client

    #Nome
    @client.name = params[:client][:name]

    #Telefone
    @client.phone_number = params[:client][:phone_number]

    #Nib
    @client.nib = params[:client][:nib]

    #Morada
    @client.address = params[:client][:address]


    if @client.save
      redirect_to client_area_index_path
    else
      flash[:error] = @client.errors.messages

      redirect_to client_area_client_path
    end



  end

  private

  def check_client

    @client = Client.find_by(user_id: current_user.id)

    if @client.nil?
      current_user.client = Client.new name: current_user.email
      current_user.save
    end

  end

end

JoiaDaEuropa/app/helpers/client_area_helper.rb
module ClientAreaHelper
end

JoiaDaEuropa/app/views/client_area/edit_client.html.erb
<!-- g4PageContent -->
<h1 align="center"><i><%= t("client_area") %></i></h1>

<br/> <br/>

<%= form_for @client, :url => url_for(:controller => 'client_area', :action => 'save_client'), html: {class: 'container'} do |f| %>
    <div class="form-group text-center">

      <label for="name"><%= t('name') %></label>
      <%= f.text_field :name %>
      <% if flash[:error] && flash[:error]['name'] %>
          <div class="alert danger"><%= flash[:error]['name'].join('<br/>') %></div>
      <% end %>

      <label for="phone_number"><%= t('phone_number') %></label>
      <%= f.text_field :phone_number %>
      <% if flash[:error] && flash[:error]['phone_number'] %>
          <div class="alert danger"><%= flash[:error]['phone_number'].join('<br/>') %></div>
      <% end %>
<br />
      <label for="nib"><%= t('nib') %></label>
      <%= f.text_field :nib %>
      <% if flash[:error] && flash[:error]['nib'] %>
          <div class="alert danger"><%= flash[:error]['nib'].join('<br/>') %></div>
      <% end %>

      <label for="address"><%= t('address') %></label>
      <%= f.text_field :address %>
      <% if flash[:error] && flash[:error]['address'] %>
          <div class="alert danger"><%= flash[:error]['address'].join('<br/>') %></div>
      <% end %>

    </div>

    <div align="right"><%= f.submit t('save')%></div>
    <button class="w2-button"><%= link_to t('cancel'), client_area_index_path%></button>

<% end %>

JoiaDaEuropa/app/views/client_area/index.html.erb
   <!-- g4PageContent -->
    <div class="col-lg-10">
      <h1><b><%= t("client_area") %></b></h1>
      <i><%= t("welcome") %></i>
      <br /><br />
      <div class="col-lg-10">
       <table class="table table-responsive" style="margin-left: -20%">
          <thead>
            <tr>
              <th><%= t("name") %></th>
              <th><%= t("phone_number") %></th>
            </tr>
          </thead>
          <tbody>
            <tr class="odd gradeX">
              <td><dt><%= @client.name %></dt> </td>
              <td><dt><%= @client.phone_number%></dt></td>
            </tr>
          </tbody>
       </table>
        <table class="table table-responsive" style="margin-left: -20%">
          <thead>
          <tr>
            <th><%= t("nib") %></th>
            <th><%= t("address") %></th>
            <th></th></td>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><dt><%= @client.nib %></dt></td>
            <td><dt><%= @client.address%></dt></td>
            <td class="w2-button"> <%= link_to t('edit'), client_area_edit_client_path %></td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>